version: '2'

services:

  postgres:
    build: ./postgres
    volumes:
      - /opt/teamcity/pg_data:/var/lib/postgresql/data
      - /opt/teamcity/pg_backup:/backups
    env_file: .env
    restart: always

  teamcity-server:
    image: jetbrains/teamcity-server
    volumes:
      - /opt/teamcity/data:/data/teamcity_server/datadir
      - /opt/teamcity/logs:/opt/teamcity/logs
    ports:
      - 8111:8111
    depends_on:
      - postgres
    env_file: .env
    restart: always

  teamcity-agent:
    image: jetbrains/teamcity-minimal-agent
    env_file: .env
    restart: always
